### PR TITLE
Fix date time creation when microtime has no decimals

### PR DESCRIPTION
**Pull request by estevejm**
This PR fixes issue discussed in #30

### CODE REVIEW

**Comment by TkachukRuslan** [comment]
@estevejm 
@bartkamphuis 
@shieldo 

Partners we have many exceptions from the test and several from the production
http://clip2net.com/s/3CbwbTn

Could you investigate this issue and  fixed this in near time

**Comment by TkachukRuslan** [comment]
@estevejm 
@bartkamphuis 
@shieldo 

Hi, we still get exceptions. We are waiting the merge.

**Comment by estevejm** [comment]
@TkachukRuslan I don't have write access, hence I can't merge it. 

I think @anyarms is one of the maintainers...

**Comment by TkachukRuslan** [comment]
@anyarms
@estevejm 
Partners if the issue was fixed please merge it.

**Comment by anyarms** [comment]
I'm no longer with Avalara, so I don't have write access anymore - sorry!
@JanzenMark can you track down the right person to review this PR?

**Comment by TkachukRuslan** [comment]
@JanzenMark 
Can you please know us the terms when will you merge  it I mean the "merge" not dev merge
Thank you

**Comment by shieldo** [comment]
You should probably just use a fork until this is merged into the main repo.

**Comment by skylord123** [comment]
I opened a case with Avalara support to start watching this repo again. We will see if that request gets answered or not.

**Comment by TkachukRuslan** [comment]
@skylord123 
Thank you. Please let us know when this issue will be merged in master.

**Comment by rahul-aggarwal-avalara** [comment]
@TkachukRuslan The code is now merged in Master branch.

**Comment by TkachukRuslan** [comment]
Hi All.

Thank you for a feedback.

I have one more issue which doesn't have fix result from developers end.
Please follow to  https://github.com/avadev/AvaTax-Calc-REST-PHP/issues/31

Let me know when the issue will be fixed ? Waiting а marge in master branch.

Waiting your response.

Ruslan Tkachuk
Project Manager
Net-Craft.com

**Comment by vijaynalawade-avalara** [comment]
Hi @TkachukRuslan ,

We are reviewing all the changes mentioned at https://github.com/avadev/AvaTax-Calc-REST-PHP/pull/33

These should be done by 18th Oct.

We'll update here as it is done.

Thanks,
Vijay

**Comment by TkachukRuslan** [comment]
Hi Vijay,

Could you please tell us how many time do you need to do with this ?

We would like to finish soon because our clients are waiting the fixes.

Thank you

Ruslan Tkachuk
Project Manager
Net-Craft.com

**Comment by vijaynalawade-avalara** [comment]
Hi @TkachukRuslan ,

Sorry for the delay. We've taken this task on priority & will merge it by 18th Nov.

Thanks,
Vijay

**Comment by TkachukRuslan** [comment]
Hi,

Vijay

Thank you for feedback.
We will be waiting updates from your end till 18th Nov or earlier.
Thank you


Ruslan Tkachuk
Project Manager
Net-Craft.com

**Comment by vijaynalawade-avalara** [comment]
Hi @TkachukRuslan,

We've updated pull requests to master branch.

Thanks,
Vijay

**Comment by TkachukRuslan** [comment]
Hi All

Thank you for updates.


Ruslan Tkachuk
Project Manager
Net-Craft.com

**Pull request merged**
